SP = float(67.83643)
RJ = float(36.67866)
MG = float(29.22988)
ES = float(27.16548)
OTS = float(19.84953)
total = float(SP + RJ + MG + ES + OTS)
print(f'O total foi de {total:.2f}%')
psp = ((SP/total)*100)
prj = ((RJ/total)*100)
pmg = ((MG/total)*100)
pes = ((ES/total)*100)
pots = ((OTS/total)*100)

print()

print(f'Porcentagem do estado de São Paulo {psp:.2f}%')
print(f'Porcentagem do estado de Rio  de Janeiro {prj:.2f}%')
print(f'Porcentagem do estado de Minas Gerais {pmg:.2f}%')
print(f'Porcentagem do estado de Espirito Santo {pes:.2f}%')
print(f'Porcentagem de Outros estados {pots:.2f}%')